"""Static bone definitions."""

from athleticspose.statics.joints import (
    h36m_joints_name_to_index,
    hj_mocap_joints_name_to_index,
    mocap_joints_name_to_index,
)

mocap_bones = [
    [mocap_joints_name_to_index["PELVIS"], mocap_joints_name_to_index["C_HIP"]],
    [mocap_joints_name_to_index["PELVIS"], mocap_joints_name_to_index["CLAV"]],
    [mocap_joints_name_to_index["C_ASIS"], mocap_joints_name_to_index["RASI"]],
    [mocap_joints_name_to_index["C_ASIS"], mocap_joints_name_to_index["LASI"]],
    [mocap_joints_name_to_index["SACR"], mocap_joints_name_to_index["RPSI"]],
    [mocap_joints_name_to_index["SACR"], mocap_joints_name_to_index["LPSI"]],
    [mocap_joints_name_to_index["C_HIP"], mocap_joints_name_to_index["RHIP"]],
    [mocap_joints_name_to_index["C_HIP"], mocap_joints_name_to_index["LHIP"]],
    [mocap_joints_name_to_index["RASI"], mocap_joints_name_to_index["RHIP"]],
    [mocap_joints_name_to_index["RASI"], mocap_joints_name_to_index["RTRO"]],
    [mocap_joints_name_to_index["RASI"], mocap_joints_name_to_index["RTHI"]],
    [mocap_joints_name_to_index["RASI"], mocap_joints_name_to_index["RHIP_Z"]],
    [mocap_joints_name_to_index["RPSI"], mocap_joints_name_to_index["RHIP"]],
    [mocap_joints_name_to_index["RPSI"], mocap_joints_name_to_index["RTRO"]],
    [mocap_joints_name_to_index["RPSI"], mocap_joints_name_to_index["RHIP_Z"]],
    [mocap_joints_name_to_index["RHIP"], mocap_joints_name_to_index["RTHI"]],
    [mocap_joints_name_to_index["RTRO"], mocap_joints_name_to_index["RTHI"]],
    [mocap_joints_name_to_index["RTHI"], mocap_joints_name_to_index["RKNE"]],
    [mocap_joints_name_to_index["RKNE"], mocap_joints_name_to_index["RKNM"]],
    [mocap_joints_name_to_index["RKNE"], mocap_joints_name_to_index["RKNL"]],
    [mocap_joints_name_to_index["RKNE"], mocap_joints_name_to_index["RTIB"]],
    [
        mocap_joints_name_to_index["RKNM"],
        mocap_joints_name_to_index["R_Medial Tibial Condyle"],
    ],
    [
        mocap_joints_name_to_index["RKNL"],
        mocap_joints_name_to_index["R_Lateral Tibial Condyle"],
    ],
    [
        mocap_joints_name_to_index["R_Medial Tibial Condyle"],
        mocap_joints_name_to_index["R_Lateral Tibial Condyle"],
    ],
    [mocap_joints_name_to_index["RTIB"], mocap_joints_name_to_index["RANK"]],
    [mocap_joints_name_to_index["RANK"], mocap_joints_name_to_index["RANM"]],
    [mocap_joints_name_to_index["RANK"], mocap_joints_name_to_index["RANL"]],
    [mocap_joints_name_to_index["RANK"], mocap_joints_name_to_index["RHEL"]],
    [mocap_joints_name_to_index["RANK"], mocap_joints_name_to_index["R_Toe"]],
    [mocap_joints_name_to_index["RANM"], mocap_joints_name_to_index["RBAM"]],
    [mocap_joints_name_to_index["RANL"], mocap_joints_name_to_index["RMT5"]],
    [mocap_joints_name_to_index["LASI"], mocap_joints_name_to_index["LPSI"]],
    [mocap_joints_name_to_index["LASI"], mocap_joints_name_to_index["LHIP"]],
    [mocap_joints_name_to_index["LASI"], mocap_joints_name_to_index["LTRO"]],
    [mocap_joints_name_to_index["LPSI"], mocap_joints_name_to_index["LHIP"]],
    [mocap_joints_name_to_index["LPSI"], mocap_joints_name_to_index["LTRO"]],
    [mocap_joints_name_to_index["LHIP"], mocap_joints_name_to_index["LTHI"]],
    [mocap_joints_name_to_index["LTRO"], mocap_joints_name_to_index["LTHI"]],
    [mocap_joints_name_to_index["LTHI"], mocap_joints_name_to_index["LKNE"]],
    [mocap_joints_name_to_index["LKNE"], mocap_joints_name_to_index["LKNM"]],
    [mocap_joints_name_to_index["LKNE"], mocap_joints_name_to_index["LKNL"]],
    [mocap_joints_name_to_index["LKNE"], mocap_joints_name_to_index["LTIB"]],
    [
        mocap_joints_name_to_index["LKNM"],
        mocap_joints_name_to_index["L_Medial Tibial Condyle"],
    ],
    [
        mocap_joints_name_to_index["LKNL"],
        mocap_joints_name_to_index["L_Lateral Tibial Condyle"],
    ],
    [
        mocap_joints_name_to_index["L_Medial Tibial Condyle"],
        mocap_joints_name_to_index["L_Lateral Tibial Condyle"],
    ],
    [mocap_joints_name_to_index["LTIB"], mocap_joints_name_to_index["LANK"]],
    [mocap_joints_name_to_index["LANK"], mocap_joints_name_to_index["LANM"]],
    [mocap_joints_name_to_index["LANK"], mocap_joints_name_to_index["LANL"]],
    [mocap_joints_name_to_index["LANK"], mocap_joints_name_to_index["LHEL"]],
    [mocap_joints_name_to_index["LANK"], mocap_joints_name_to_index["L_Toe"]],
    [mocap_joints_name_to_index["LANM"], mocap_joints_name_to_index["LBAM"]],
    [mocap_joints_name_to_index["LANL"], mocap_joints_name_to_index["LMT5"]],
    [mocap_joints_name_to_index["Xiphoid"], mocap_joints_name_to_index["RRIB"]],
    [mocap_joints_name_to_index["Xiphoid"], mocap_joints_name_to_index["LRIB"]],
    [mocap_joints_name_to_index["T10"], mocap_joints_name_to_index["RRIB"]],
    [mocap_joints_name_to_index["T10"], mocap_joints_name_to_index["LRIB"]],
    [mocap_joints_name_to_index["Manubrium"], mocap_joints_name_to_index["LSHF"]],
    [mocap_joints_name_to_index["Manubrium"], mocap_joints_name_to_index["RSHF"]],
    [mocap_joints_name_to_index["CLAV"], mocap_joints_name_to_index["EARC"]],
    [mocap_joints_name_to_index["CLAV"], mocap_joints_name_to_index["LSHO"]],
    [mocap_joints_name_to_index["CLAV"], mocap_joints_name_to_index["RSHO"]],
    [mocap_joints_name_to_index["C7"], mocap_joints_name_to_index["LSHB"]],
    [mocap_joints_name_to_index["C7"], mocap_joints_name_to_index["RSHB"]],
    [mocap_joints_name_to_index["EARC"], mocap_joints_name_to_index["Vertex"]],
    [mocap_joints_name_to_index["Nasion"], mocap_joints_name_to_index["REAR"]],
    [mocap_joints_name_to_index["Nasion"], mocap_joints_name_to_index["LEAR"]],
    [mocap_joints_name_to_index["BHED"], mocap_joints_name_to_index["REAR"]],
    [mocap_joints_name_to_index["BHED"], mocap_joints_name_to_index["LEAR"]],
    [
        mocap_joints_name_to_index["L_Shoulder Joint"],
        mocap_joints_name_to_index["LSHF"],
    ],
    [
        mocap_joints_name_to_index["L_Shoulder Joint"],
        mocap_joints_name_to_index["LSHB"],
    ],
    [
        mocap_joints_name_to_index["L_Shoulder Joint"],
        mocap_joints_name_to_index["LUPA"],
    ],
    [
        mocap_joints_name_to_index["L_Shoulder Joint"],
        mocap_joints_name_to_index["LELB"],
    ],
    [mocap_joints_name_to_index["LSHO"], mocap_joints_name_to_index["LSHF"]],
    [mocap_joints_name_to_index["LSHO"], mocap_joints_name_to_index["LSHB"]],
    [mocap_joints_name_to_index["LELB"], mocap_joints_name_to_index["LELL"]],
    [mocap_joints_name_to_index["LELB"], mocap_joints_name_to_index["LELM"]],
    [mocap_joints_name_to_index["LELB"], mocap_joints_name_to_index["LWRT"]],
    [mocap_joints_name_to_index["LFRA"], mocap_joints_name_to_index["LELL"]],
    [mocap_joints_name_to_index["LFRA"], mocap_joints_name_to_index["LELM"]],
    [mocap_joints_name_to_index["LWRT"], mocap_joints_name_to_index["LWSL"]],
    [mocap_joints_name_to_index["LWRT"], mocap_joints_name_to_index["LWSM"]],
    [mocap_joints_name_to_index["LWRT"], mocap_joints_name_to_index["LHND"]],
    [mocap_joints_name_to_index["LWSL"], mocap_joints_name_to_index["LMP2"]],
    [mocap_joints_name_to_index["LWSM"], mocap_joints_name_to_index["LMP5"]],
    [
        mocap_joints_name_to_index["R_Shoulder Joint"],
        mocap_joints_name_to_index["RSHF"],
    ],
    [
        mocap_joints_name_to_index["R_Shoulder Joint"],
        mocap_joints_name_to_index["RSHB"],
    ],
    [
        mocap_joints_name_to_index["R_Shoulder Joint"],
        mocap_joints_name_to_index["RUPA"],
    ],
    [mocap_joints_name_to_index["RSHO"], mocap_joints_name_to_index["RSHF"]],
    [mocap_joints_name_to_index["RSHO"], mocap_joints_name_to_index["RSHB"]],
    [mocap_joints_name_to_index["RUPA"], mocap_joints_name_to_index["RELB"]],
    [mocap_joints_name_to_index["RELB"], mocap_joints_name_to_index["RELL"]],
    [mocap_joints_name_to_index["RELB"], mocap_joints_name_to_index["RELM"]],
    [mocap_joints_name_to_index["RELB"], mocap_joints_name_to_index["RWRT"]],
    [mocap_joints_name_to_index["RFRA"], mocap_joints_name_to_index["RELL"]],
    [mocap_joints_name_to_index["RFRA"], mocap_joints_name_to_index["RELM"]],
    [mocap_joints_name_to_index["RWRT"], mocap_joints_name_to_index["RWSL"]],
    [mocap_joints_name_to_index["RWRT"], mocap_joints_name_to_index["RWSM"]],
    [mocap_joints_name_to_index["RWRT"], mocap_joints_name_to_index["RHND"]],
    [mocap_joints_name_to_index["RWSL"], mocap_joints_name_to_index["RMP2"]],
    [mocap_joints_name_to_index["RWSM"], mocap_joints_name_to_index["RMP5"]],
]

hj_mocap_bones = [
    [hj_mocap_joints_name_to_index["LPSI"], hj_mocap_joints_name_to_index["LumbarJC"]],
    [hj_mocap_joints_name_to_index["RPSI"], hj_mocap_joints_name_to_index["LumbarJC"]],
    [hj_mocap_joints_name_to_index["LASI"], hj_mocap_joints_name_to_index["LumbarJC"]],
    [hj_mocap_joints_name_to_index["LASI"], hj_mocap_joints_name_to_index["LhipC"]],
    [hj_mocap_joints_name_to_index["RASI"], hj_mocap_joints_name_to_index["LumbarJC"]],
    [hj_mocap_joints_name_to_index["RASI"], hj_mocap_joints_name_to_index["RhipC"]],
    [hj_mocap_joints_name_to_index["RASI"], hj_mocap_joints_name_to_index["LASI"]],
    [hj_mocap_joints_name_to_index["RtopILUM"], hj_mocap_joints_name_to_index["RASI"]],
    [hj_mocap_joints_name_to_index["RtopILUM"], hj_mocap_joints_name_to_index["RPSI"]],
    [hj_mocap_joints_name_to_index["LtopILUM"], hj_mocap_joints_name_to_index["LASI"]],
    [hj_mocap_joints_name_to_index["LtopILUM"], hj_mocap_joints_name_to_index["LPSI"]],
    [hj_mocap_joints_name_to_index["LumbarJC"], hj_mocap_joints_name_to_index["T12"]],
    [hj_mocap_joints_name_to_index["T12"], hj_mocap_joints_name_to_index["T8"]],
    [hj_mocap_joints_name_to_index["T8"], hj_mocap_joints_name_to_index["ThoracicJC"]],
    [
        hj_mocap_joints_name_to_index["ThoracicJC"],
        hj_mocap_joints_name_to_index["XIPF"],
    ],
    [
        hj_mocap_joints_name_to_index["ThoracicJC"],
        hj_mocap_joints_name_to_index["LumbarJC"],
    ],
    [hj_mocap_joints_name_to_index["XIPF"], hj_mocap_joints_name_to_index["STEF"]],
    [hj_mocap_joints_name_to_index["XIPF"], hj_mocap_joints_name_to_index["RRIB"]],
    [hj_mocap_joints_name_to_index["XIPF"], hj_mocap_joints_name_to_index["LRIB"]],
    [hj_mocap_joints_name_to_index["ThoracicJC"], hj_mocap_joints_name_to_index["C7"]],
    [
        hj_mocap_joints_name_to_index["ThoracicJC"],
        hj_mocap_joints_name_to_index["RRIB"],
    ],
    [
        hj_mocap_joints_name_to_index["ThoracicJC"],
        hj_mocap_joints_name_to_index["LRIB"],
    ],
    [hj_mocap_joints_name_to_index["RRIB"], hj_mocap_joints_name_to_index["LRIB"]],
    [hj_mocap_joints_name_to_index["C7"], hj_mocap_joints_name_to_index["NeckC"]],
    [hj_mocap_joints_name_to_index["C7"], hj_mocap_joints_name_to_index["Top_HEAD"]],
    [hj_mocap_joints_name_to_index["C7"], hj_mocap_joints_name_to_index["Front_HEAD"]],
    [hj_mocap_joints_name_to_index["NeckC"], hj_mocap_joints_name_to_index["STEF"]],
    [hj_mocap_joints_name_to_index["REAR"], hj_mocap_joints_name_to_index["LEAR"]],
    [
        hj_mocap_joints_name_to_index["Top_HEAD"],
        hj_mocap_joints_name_to_index["Front_HEAD"],
    ],
    [hj_mocap_joints_name_to_index["Top_HEAD"], hj_mocap_joints_name_to_index["REAR"]],
    [hj_mocap_joints_name_to_index["Top_HEAD"], hj_mocap_joints_name_to_index["LEAR"]],
    [
        hj_mocap_joints_name_to_index["Front_HEAD"],
        hj_mocap_joints_name_to_index["REAR"],
    ],
    [
        hj_mocap_joints_name_to_index["Front_HEAD"],
        hj_mocap_joints_name_to_index["LEAR"],
    ],
    [hj_mocap_joints_name_to_index["RSHA"], hj_mocap_joints_name_to_index["C7"]],
    [
        hj_mocap_joints_name_to_index["RSHA"],
        hj_mocap_joints_name_to_index["RshoulderC"],
    ],
    [
        hj_mocap_joints_name_to_index["RshoulderC"],
        hj_mocap_joints_name_to_index["RELB"],
    ],
    [hj_mocap_joints_name_to_index["RELB"], hj_mocap_joints_name_to_index["RELL"]],
    [hj_mocap_joints_name_to_index["RELB"], hj_mocap_joints_name_to_index["RELM"]],
    [hj_mocap_joints_name_to_index["RELB"], hj_mocap_joints_name_to_index["RWST"]],
    [hj_mocap_joints_name_to_index["RWST"], hj_mocap_joints_name_to_index["RWRL"]],
    [hj_mocap_joints_name_to_index["RWST"], hj_mocap_joints_name_to_index["RWRM"]],
    [hj_mocap_joints_name_to_index["RWST"], hj_mocap_joints_name_to_index["RHND"]],
    [hj_mocap_joints_name_to_index["RWRL"], hj_mocap_joints_name_to_index["RHND"]],
    [hj_mocap_joints_name_to_index["RWRM"], hj_mocap_joints_name_to_index["RHND"]],
    [hj_mocap_joints_name_to_index["LSHA"], hj_mocap_joints_name_to_index["C7"]],
    [
        hj_mocap_joints_name_to_index["LSHA"],
        hj_mocap_joints_name_to_index["LshoulderC"],
    ],
    [
        hj_mocap_joints_name_to_index["LshoulderC"],
        hj_mocap_joints_name_to_index["LELB"],
    ],
    [hj_mocap_joints_name_to_index["LELB"], hj_mocap_joints_name_to_index["LELL"]],
    [hj_mocap_joints_name_to_index["LELB"], hj_mocap_joints_name_to_index["LELM"]],
    [hj_mocap_joints_name_to_index["LELB"], hj_mocap_joints_name_to_index["LWST"]],
    [hj_mocap_joints_name_to_index["LWST"], hj_mocap_joints_name_to_index["LWRL"]],
    [hj_mocap_joints_name_to_index["LWST"], hj_mocap_joints_name_to_index["LWRM"]],
    [hj_mocap_joints_name_to_index["LWST"], hj_mocap_joints_name_to_index["LHND"]],
    [hj_mocap_joints_name_to_index["LWRL"], hj_mocap_joints_name_to_index["LHND"]],
    [hj_mocap_joints_name_to_index["LWRM"], hj_mocap_joints_name_to_index["LHND"]],
    [hj_mocap_joints_name_to_index["RhipC"], hj_mocap_joints_name_to_index["RkneeC"]],
    [hj_mocap_joints_name_to_index["RkneeC"], hj_mocap_joints_name_to_index["RKNL"]],
    [hj_mocap_joints_name_to_index["RkneeC"], hj_mocap_joints_name_to_index["RKNM"]],
    [hj_mocap_joints_name_to_index["RkneeC"], hj_mocap_joints_name_to_index["RankleC"]],
    [hj_mocap_joints_name_to_index["RankleC"], hj_mocap_joints_name_to_index["RTOE"]],
    [hj_mocap_joints_name_to_index["RankleC"], hj_mocap_joints_name_to_index["RHEL"]],
    [hj_mocap_joints_name_to_index["RankleC"], hj_mocap_joints_name_to_index["RBAL"]],
    [hj_mocap_joints_name_to_index["RankleC"], hj_mocap_joints_name_to_index["RBAM"]],
    [hj_mocap_joints_name_to_index["LhipC"], hj_mocap_joints_name_to_index["LkneeC"]],
    [hj_mocap_joints_name_to_index["LkneeC"], hj_mocap_joints_name_to_index["LKNL"]],
    [hj_mocap_joints_name_to_index["LkneeC"], hj_mocap_joints_name_to_index["LKNM"]],
    [hj_mocap_joints_name_to_index["LkneeC"], hj_mocap_joints_name_to_index["LankleC"]],
    [hj_mocap_joints_name_to_index["LankleC"], hj_mocap_joints_name_to_index["LTOE"]],
    [hj_mocap_joints_name_to_index["LankleC"], hj_mocap_joints_name_to_index["LHEL"]],
    [hj_mocap_joints_name_to_index["LankleC"], hj_mocap_joints_name_to_index["LBAL"]],
    [hj_mocap_joints_name_to_index["LankleC"], hj_mocap_joints_name_to_index["LBAM"]],
    [
        hj_mocap_joints_name_to_index["Prox"],
        hj_mocap_joints_name_to_index["ProxGround"],
    ],
    [hj_mocap_joints_name_to_index["Prox"], hj_mocap_joints_name_to_index["Dist"]],
    [
        hj_mocap_joints_name_to_index["Dist"],
        hj_mocap_joints_name_to_index["DistGround"],
    ],
]

h36m_bones = [
    [h36m_joints_name_to_index["PELVIS"], h36m_joints_name_to_index["R_HIP"]],
    [h36m_joints_name_to_index["PELVIS"], h36m_joints_name_to_index["L_HIP"]],
    [h36m_joints_name_to_index["R_HIP"], h36m_joints_name_to_index["R_KNEE"]],
    [h36m_joints_name_to_index["L_HIP"], h36m_joints_name_to_index["L_KNEE"]],
    [h36m_joints_name_to_index["R_KNEE"], h36m_joints_name_to_index["R_ANKLE"]],
    [h36m_joints_name_to_index["L_KNEE"], h36m_joints_name_to_index["L_ANKLE"]],
    [h36m_joints_name_to_index["PELVIS"], h36m_joints_name_to_index["SPINE"]],
    [h36m_joints_name_to_index["SPINE"], h36m_joints_name_to_index["THORAX"]],
    [h36m_joints_name_to_index["THORAX"], h36m_joints_name_to_index["NECK"]],
    [h36m_joints_name_to_index["NECK"], h36m_joints_name_to_index["HEAD"]],
    [h36m_joints_name_to_index["THORAX"], h36m_joints_name_to_index["R_SHOULDER"]],
    [h36m_joints_name_to_index["THORAX"], h36m_joints_name_to_index["L_SHOULDER"]],
    [h36m_joints_name_to_index["R_SHOULDER"], h36m_joints_name_to_index["R_ELBOW"]],
    [h36m_joints_name_to_index["L_SHOULDER"], h36m_joints_name_to_index["L_ELBOW"]],
    [h36m_joints_name_to_index["R_ELBOW"], h36m_joints_name_to_index["R_WRIST"]],
    [h36m_joints_name_to_index["L_ELBOW"], h36m_joints_name_to_index["L_WRIST"]],
]
