"""Static joint definitions."""

mocap_joints_name_to_index = {
    "PELVIS": 0,
    "C_ASIS": 1,
    "SACR": 2,
    "C_HIP": 3,
    "RASI": 4,
    "RPSI": 5,
    "RHIP": 6,
    "RTRO": 7,
    "RTHI": 8,
    "RKNE": 9,
    "RKNM": 10,
    "RKNL": 11,
    "R_Medial Tibial Condyle": 12,
    "R_Lateral Tibial Condyle": 13,
    "RTIB": 14,
    "RANK": 15,
    "RANM": 16,
    "RANL": 17,
    "RHEL": 18,
    "R_Toe": 19,
    "RBAM": 20,
    "RMT5": 21,
    "LASI": 22,
    "LPSI": 23,
    "LHIP": 24,
    "LTRO": 25,
    "LTHI": 26,
    "LKNE": 27,
    "LKNM": 28,
    "LKNL": 29,
    "L_Medial Tibial Condyle": 30,
    "L_Lateral Tibial Condyle": 31,
    "LTIB": 32,
    "LANK": 33,
    "LANM": 34,
    "LANL": 35,
    "LHEL": 36,
    "L_Toe": 37,
    "LBAM": 38,
    "LMT5": 39,
    "Xiphoid": 40,
    "T10": 41,
    "RRIB": 42,
    "LRIB": 43,
    "Manubrium": 44,
    "CLAV": 45,
    "C7": 46,
    "EARC": 47,
    "Nasion": 48,
    "BHED": 49,
    "REAR": 50,
    "LEAR": 51,
    "Vertex": 52,
    "L_Shoulder Joint": 53,
    "LSHO": 54,
    "LSHF": 55,
    "LSHB": 56,
    "LUPA": 57,
    "LELB": 58,
    "LFRA": 59,
    "LELL": 60,
    "LELM": 61,
    "LWRT": 62,
    "LWSL": 63,
    "LWSM": 64,
    "LHND": 65,
    "LMP2": 66,
    "LMP5": 67,
    "R_Shoulder Joint": 68,
    "RSHO": 69,
    "RSHF": 70,
    "RSHB": 71,
    "RUPA": 72,
    "RELB": 73,
    "RFRA": 74,
    "RELL": 75,
    "RELM": 76,
    "RWRT": 77,
    "RWSL": 78,
    "RWSM": 79,
    "RHND": 80,
    "RMP2": 81,
    "RMP5": 82,
    "RHIP_Z": 83,
}

joint_index_h36m_to_mocap = {
    0: [mocap_joints_name_to_index["PELVIS"]],
    1: [mocap_joints_name_to_index["RASI"], mocap_joints_name_to_index["RPSI"]],
    2: [mocap_joints_name_to_index["RKNE"]],
    3: [mocap_joints_name_to_index["RANK"]],
    4: [mocap_joints_name_to_index["LASI"], mocap_joints_name_to_index["LPSI"]],
    5: [mocap_joints_name_to_index["LKNE"]],
    6: [mocap_joints_name_to_index["LANK"]],
    7: [mocap_joints_name_to_index["Xiphoid"], mocap_joints_name_to_index["T10"]],
    8: [mocap_joints_name_to_index["CLAV"]],
    9: [mocap_joints_name_to_index["CLAV"], mocap_joints_name_to_index["Nasion"]],
    10: [mocap_joints_name_to_index["Vertex"], mocap_joints_name_to_index["EARC"]],
    11: [mocap_joints_name_to_index["L_Shoulder Joint"]],
    12: [mocap_joints_name_to_index["LELB"]],
    13: [mocap_joints_name_to_index["LWRT"]],
    14: [mocap_joints_name_to_index["R_Shoulder Joint"]],
    15: [mocap_joints_name_to_index["RELB"]],
    16: [mocap_joints_name_to_index["RWRT"]],
}

joint_index_coco_to_mocap = {
    0: [mocap_joints_name_to_index["CLAV"], mocap_joints_name_to_index["Nasion"]],
    1: [],
    2: [],
    3: [],
    4: [],
    5: [mocap_joints_name_to_index["L_Shoulder Joint"]],
    6: [mocap_joints_name_to_index["R_Shoulder Joint"]],
    7: [mocap_joints_name_to_index["LELB"]],
    8: [mocap_joints_name_to_index["RELB"]],
    9: [mocap_joints_name_to_index["LWRT"]],
    10: [mocap_joints_name_to_index["RWRT"]],
    11: [mocap_joints_name_to_index["LASI"], mocap_joints_name_to_index["LPSI"]],
    12: [mocap_joints_name_to_index["RASI"], mocap_joints_name_to_index["RPSI"]],
    13: [mocap_joints_name_to_index["LKNE"]],
    14: [mocap_joints_name_to_index["RKNE"]],
    15: [mocap_joints_name_to_index["LANK"]],
    16: [mocap_joints_name_to_index["RANK"]],
}
