defaults:
  - data: all
  - model: base
  - evaluation: default
  - prediction: null
  - _self_

wandb:
  project: AthleticsPose

hydra:
  run:
    dir: work_dir/${exp_name}/${now:%Y%m%d}-${now:%H%M%S}
  sweep:
    dir: multirun/${exp_name}/${now:%Y%m%d}-${now:%H%M%S}

datamodule:
  batch_size: 16

exp_name: your_experiment

trainer:
  accelerator: "gpu"
  devices: 1
  precision: "bf16"
  max_epochs: 200
  min_epochs: 100

train:
  lr: 5e-4
  lr_decay: 0.99
  weight_decay: 0.01

seed: 42
